FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install schedule

COPY . .

# 使排程器一直運行
CMD ["python", "run.daily.py"]
