services:
  mysql:
    image: mysql:8.0
    container_name: exchange-mysql
    restart: always
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: "Chrisxx666"
      MYSQL_DATABASE: "exchange_db"
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pChrisxx666"]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    build: .
    container_name: exchange-etl
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "Chrisxx666"
      DB_NAME: "exchange_db"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: exchange-scheduler
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "Chrisxx666"
      DB_NAME: "exchange_db"

volumes:
  mysql-data:
